### ISSUE TITLE
Default install

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/BlazeIterative#25]
Here is how I installed:

RUN git clone https://github.com/STEllAR-GROUP/BlazeIterative
WORKDIR /BlazeIterative/build
RUN cmake ..
RUN make install

Everything went in /usr/local/include/BlazeIteratative.

With a file named x.c containing

#include <BlazeIterative.hpp>

I get this error:

$ g++ -o x x.cc
x.cc:1:10: fatal error: BlazeIteratave/BlazeIterative.hpp: No such file or directory
    1 | #include <BlazeIteratave/BlazeIterative.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

With a file containing:

#include <BlazeIteratave/BlazeIterative.hpp>

$ g++ -o x x.cc
In file included from /usr/local/include/BlazeIterative/solvers/solvers.hpp:10,
                 from /usr/local/include/BlazeIterative/solve.hpp:12,
                 from /usr/local/include/BlazeIterative/BlazeIterative.hpp:12,
                 from x.cc:1:
/usr/local/include/BlazeIterative/solvers/ConjugateGradientTag.hpp:9:10: fatal error: IterativeCommon.hpp: No such file or directory
    9 | #include "IterativeCommon.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

What works is the to use

#include <BlazeIterative.hpp>

and compile as follows:

$ g++ -o x x.cc -I/usr/local/include/BlazeIterative

IMHO, this is not correct default behavior. Instead of defaulting the install to /usr/local/include/BlazeIterative it should go to /usr/local/include.

**Comment by diehlpk** [comment]
@stevenrbrandt Could you please post the output of `ls -lah /usr/local/include/BlazeIterative`?

**Comment by stevenrbrandt** [comment]
```
$  ls -lah /usr/local/include/BlazeIterative
total 36K
drwxr-xr-x.  3 root root 4.0K Jun  2 15:21 .
drwxr-xr-x.  8 root root 4.0K Jun  2 15:21 ..
-rw-r--r--. 13 root root  533 Jun  2 15:20 BlazeIterative.hpp
-rw-r--r--. 13 root root  563 Jun  2 15:20 IterativeCommon.hpp
-rw-r--r--. 13 root root 2.8K Jun  2 15:20 IterativeTag.hpp
-rw-r--r--. 13 root root  653 Jun  2 15:20 TerminationStatus.hpp
-rw-r--r--. 13 root root 6.4K Jun  2 15:20 solve.hpp
drwxr-xr-x.  2 root root 4.0K Jun  2 15:21 solvers
```

**Comment by diehlpk** [comment]
@stevenrbrandt Please check #26

Now, you should be able to include <BlazeIterative.h> and there is no need to add the -I to the g++.

**Comment by diehlpk** [comment]
#26 fixed the issue.
